language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - 'iojs'
before_install:
  - npm update -g npm
before_script:
  - cd data
  - sh download.sh
  - cd ..
after_script:
  - npm run coveralls
